project:
  type: website
  output-dir: docs

website:
  title: "My Quarto Blog"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Hello Post"
        href: hello.ipynb  # Link directly to the notebook

format:
  html:
    toc: true  # Adds a table of contents